.PHONY:		all valg time install uninstall clean


all:
		./suite.sh

valg:
		VALG=Y ./suite.sh

time:
		VALG=T ./suite.sh

install:

uninstall:

clean:
		rm -f output/* valg_log.txt input/part* input/empty
