include		../_conf.txt


.PHONY:		all valg time install uninstall clean


all:
		$(SUITE)

valg:
		VALG=Y $(SUITE)

time:
		VALG=T $(SUITE)

install:

uninstall:

clean:
		rm -f output/* valg_log.txt log.txt input/part* input/empty
